### ISSUE TITLE
As a POI Manager I want to have online the POI-Beacon mapper webapp in order to be able to understand if the Beacon related POI is the right one.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-tourismpoimapping-demo-webapp#2]
The link to the development webapp is:
http://demo.beacons.dev.atmosfera.io/index.html
- [x] Create a repository for each separate web component
> https://github.com/noi-techpark/webcomp-beacon-pois-map
> https://github.com/noi-techpark/webcomp-beacon-pois-table
> UPDATE: We decided to keep this webcomponent as a single repo inside https://github.com/noi-techpark/webcomp-beacons-map-table
- [x] Rampanelli will upload the source code to the repository
- [x] We add a docker configuration and update the README
- [x] the publication pipeline needs to be created
- [x] publish components https://webcomponents.opendatahub.bz.it/beacons-map-table
- [x] publish landing page under maps.beacon.bz.it

**Comment by sseppi** [comment]
.

**Comment by Piiit** [comment]
@sseppi All done, please test.
